//! Generator metadata for the fake data command

/// Information about a fake data generator
#[derive(Clone)]
pub struct GeneratorInfo {
  pub name: &'static str,
  pub category: &'static str,
  pub description: &'static str,
  pub example: &'static str,
  pub params: &'static str,
}

/// Get all available generators with their metadata
pub fn get_all_generators() -> Vec<GeneratorInfo> {
  vec![
    // Identity
    GeneratorInfo {
      name: "name",
      category: "identity",
      description: "Full name (first + last)",
      example: "John Smith",
      params: "",
    },
    GeneratorInfo {
      name: "first_name",
      category: "identity",
      description: "First name only",
      example: "John",
      params: "",
    },
    GeneratorInfo {
      name: "last_name",
      category: "identity",
      description: "Last name only",
      example: "Smith",
      params: "",
    },
    GeneratorInfo {
      name: "username",
      category: "identity",
      description: "Username",
      example: "john_smith42",
      params: "",
    },
    GeneratorInfo {
      name: "password",
      category: "identity",
      description: "Random password",
      example: "xK9#mP2$vL",
      params: "",
    },
    GeneratorInfo {
      name: "title",
      category: "identity",
      description: "Title (Mr., Mrs., Dr.)",
      example: "Mr.",
      params: "",
    },
    GeneratorInfo {
      name: "suffix",
      category: "identity",
      description: "Name suffix (Jr., Sr., III)",
      example: "Jr.",
      params: "",
    },
    // Contact
    GeneratorInfo {
      name: "email",
      category: "contact",
      description: "Email address",
      example: "john.smith@example.com",
      params: "",
    },
    GeneratorInfo {
      name: "free_email",
      category: "contact",
      description: "Free email (gmail, yahoo)",
      example: "john.smith@gmail.com",
      params: "",
    },
    GeneratorInfo {
      name: "phone",
      category: "contact",
      description: "Phone number",
      example: "(555) 123-4567",
      params: "",
    },
    GeneratorInfo {
      name: "cell_phone",
      category: "contact",
      description: "Cell phone number",
      example: "(555) 987-6543",
      params: "",
    },
    // Company
    GeneratorInfo {
      name: "company",
      category: "company",
      description: "Company name",
      example: "TechCorp Industries",
      params: "",
    },
    GeneratorInfo {
      name: "company_suffix",
      category: "company",
      description: "Company suffix",
      example: "Inc.",
      params: "",
    },
    GeneratorInfo {
      name: "job_title",
      category: "company",
      description: "Job title/profession",
      example: "Software Engineer",
      params: "",
    },
    GeneratorInfo {
      name: "industry",
      category: "company",
      description: "Industry name",
      example: "Technology",
      params: "",
    },
    GeneratorInfo {
      name: "job_field",
      category: "company",
      description: "Job field",
      example: "Engineering",
      params: "",
    },
    GeneratorInfo {
      name: "job_position",
      category: "company",
      description: "Job position level",
      example: "Manager",
      params: "",
    },
    GeneratorInfo {
      name: "job_seniority",
      category: "company",
      description: "Seniority level",
      example: "Senior",
      params: "",
    },
    // Internet
    GeneratorInfo {
      name: "url",
      category: "internet",
      description: "Full URL",
      example: "https://example.com/page",
      params: "",
    },
    GeneratorInfo {
      name: "domain",
      category: "internet",
      description: "Domain name",
      example: "example.com",
      params: "",
    },
    GeneratorInfo {
      name: "ipv4",
      category: "internet",
      description: "IPv4 address",
      example: "192.168.1.1",
      params: "",
    },
    GeneratorInfo {
      name: "ipv6",
      category: "internet",
      description: "IPv6 address",
      example: "2001:0db8:85a3::8a2e:0370:7334",
      params: "",
    },
    GeneratorInfo {
      name: "mac_address",
      category: "internet",
      description: "MAC address",
      example: "00:1A:2B:3C:4D:5E",
      params: "",
    },
    GeneratorInfo {
      name: "user_agent",
      category: "internet",
      description: "Browser user agent",
      example: "Mozilla/5.0...",
      params: "",
    },
    GeneratorInfo {
      name: "color",
      category: "internet",
      description: "Hex color code",
      example: "#FF5722",
      params: "",
    },
    // Finance
    GeneratorInfo {
      name: "credit_card",
      category: "finance",
      description: "Credit card number",
      example: "4532015112830366",
      params: "",
    },
    GeneratorInfo {
      name: "currency_code",
      category: "finance",
      description: "Currency code",
      example: "USD",
      params: "",
    },
    GeneratorInfo {
      name: "currency_name",
      category: "finance",
      description: "Currency name",
      example: "US Dollar",
      params: "",
    },
    GeneratorInfo {
      name: "currency_symbol",
      category: "finance",
      description: "Currency symbol",
      example: "$",
      params: "",
    },
    GeneratorInfo {
      name: "price",
      category: "finance",
      description: "Random price",
      example: "42.99",
      params: "--min, --max",
    },
    GeneratorInfo {
      name: "amount",
      category: "finance",
      description: "Formatted amount",
      example: "1,234.56",
      params: "",
    },
    // DateTime
    GeneratorInfo {
      name: "date",
      category: "datetime",
      description: "Full datetime (RFC3339)",
      example: "2024-01-15T10:30:45Z",
      params: "",
    },
    GeneratorInfo {
      name: "time",
      category: "datetime",
      description: "Time only",
      example: "10:30:45",
      params: "",
    },
    GeneratorInfo {
      name: "iso_date",
      category: "datetime",
      description: "ISO date only",
      example: "2024-01-15",
      params: "",
    },
    GeneratorInfo {
      name: "unix_timestamp",
      category: "datetime",
      description: "Unix timestamp",
      example: "1705318245",
      params: "",
    },
    GeneratorInfo {
      name: "relative_time",
      category: "datetime",
      description: "Relative time string",
      example: "2 hours ago",
      params: "",
    },
    // Location
    GeneratorInfo {
      name: "street",
      category: "location",
      description: "Street name",
      example: "Main Street",
      params: "",
    },
    GeneratorInfo {
      name: "street_address",
      category: "location",
      description: "Full street address",
      example: "123 Main St",
      params: "",
    },
    GeneratorInfo {
      name: "city",
      category: "location",
      description: "City name",
      example: "New York",
      params: "",
    },
    GeneratorInfo {
      name: "state",
      category: "location",
      description: "State name",
      example: "California",
      params: "",
    },
    GeneratorInfo {
      name: "state_abbr",
      category: "location",
      description: "State abbreviation",
      example: "CA",
      params: "",
    },
    GeneratorInfo {
      name: "zip",
      category: "location",
      description: "ZIP code",
      example: "90210",
      params: "",
    },
    GeneratorInfo {
      name: "country",
      category: "location",
      description: "Country name",
      example: "United States",
      params: "",
    },
    GeneratorInfo {
      name: "country_code",
      category: "location",
      description: "Country code",
      example: "US",
      params: "",
    },
    GeneratorInfo {
      name: "latitude",
      category: "location",
      description: "Geographic latitude",
      example: "40.7128",
      params: "",
    },
    GeneratorInfo {
      name: "longitude",
      category: "location",
      description: "Geographic longitude",
      example: "-74.0060",
      params: "",
    },
    // Text
    GeneratorInfo {
      name: "word",
      category: "text",
      description: "Single word",
      example: "lorem",
      params: "",
    },
    GeneratorInfo {
      name: "words",
      category: "text",
      description: "Multiple words",
      example: "lorem ipsum dolor",
      params: "-w/--words",
    },
    GeneratorInfo {
      name: "sentence",
      category: "text",
      description: "Sentence",
      example: "Lorem ipsum dolor sit amet.",
      params: "-w/--words",
    },
    GeneratorInfo {
      name: "paragraph",
      category: "text",
      description: "Paragraph",
      example: "Lorem ipsum dolor sit amet...",
      params: "-w/--words (sentences)",
    },
    GeneratorInfo {
      name: "slug",
      category: "text",
      description: "URL-friendly slug",
      example: "lorem-ipsum-dolor",
      params: "",
    },
    GeneratorInfo {
      name: "alphanumeric",
      category: "text",
      description: "Random alphanumeric string",
      example: "a1b2c3d4e5",
      params: "-l/--length",
    },
    // Identifiers
    GeneratorInfo {
      name: "uuid",
      category: "identifiers",
      description: "UUID v4",
      example: "550e8400-e29b-41d4-a716-446655440000",
      params: "",
    },
    GeneratorInfo {
      name: "token",
      category: "identifiers",
      description: "32-char token",
      example: "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6",
      params: "",
    },
    GeneratorInfo {
      name: "numeric_id",
      category: "identifiers",
      description: "Numeric ID (10-13 digits)",
      example: "1234567890123",
      params: "",
    },
    GeneratorInfo {
      name: "short_hash",
      category: "identifiers",
      description: "Short hash (git-style)",
      example: "a1b2c3d",
      params: "",
    },
    GeneratorInfo {
      name: "sha256",
      category: "identifiers",
      description: "SHA-256 hash",
      example: "3f78c4d0f5e6a7b8...",
      params: "",
    },
    GeneratorInfo {
      name: "md5",
      category: "identifiers",
      description: "MD5 hash",
      example: "d41d8cd98f00b204...",
      params: "",
    },
    GeneratorInfo {
      name: "base64",
      category: "identifiers",
      description: "Base64 string",
      example: "SGVsbG8gV29ybGQ=",
      params: "",
    },
    GeneratorInfo {
      name: "jwt",
      category: "identifiers",
      description: "JWT-like token",
      example: "eyJhbGciOi...",
      params: "",
    },
    GeneratorInfo {
      name: "isbn",
      category: "identifiers",
      description: "ISBN-10",
      example: "0-123-45678-9",
      params: "",
    },
    GeneratorInfo {
      name: "isbn13",
      category: "identifiers",
      description: "ISBN-13",
      example: "978-0-123-45678-6",
      params: "",
    },
    GeneratorInfo {
      name: "etag",
      category: "identifiers",
      description: "HTTP ETag",
      example: "\"abc123def456\"",
      params: "",
    },
    // Web
    GeneratorInfo {
      name: "boolean",
      category: "web",
      description: "Random boolean",
      example: "true",
      params: "",
    },
    GeneratorInfo {
      name: "filename",
      category: "web",
      description: "Filename with extension",
      example: "document.pdf",
      params: "",
    },
    GeneratorInfo {
      name: "file_size",
      category: "web",
      description: "File size in bytes",
      example: "1048576",
      params: "--min, --max",
    },
    GeneratorInfo {
      name: "mime_type",
      category: "web",
      description: "MIME type",
      example: "application/json",
      params: "",
    },
    GeneratorInfo {
      name: "file_extension",
      category: "web",
      description: "File extension",
      example: "pdf",
      params: "",
    },
    GeneratorInfo {
      name: "version",
      category: "web",
      description: "Semantic version",
      example: "1.2.3",
      params: "",
    },
    GeneratorInfo {
      name: "semver",
      category: "web",
      description: "Semantic version",
      example: "1.2.3",
      params: "",
    },
    GeneratorInfo {
      name: "hex_color",
      category: "web",
      description: "Hex color",
      example: "#FF5722",
      params: "",
    },
    GeneratorInfo {
      name: "rgb_color",
      category: "web",
      description: "RGB color",
      example: "rgb(255, 87, 34)",
      params: "",
    },
    GeneratorInfo {
      name: "locale",
      category: "web",
      description: "Locale code",
      example: "en-US",
      params: "",
    },
    GeneratorInfo {
      name: "timezone",
      category: "web",
      description: "Timezone name",
      example: "America/New_York",
      params: "",
    },
    GeneratorInfo {
      name: "number",
      category: "web",
      description: "Random integer",
      example: "42",
      params: "--min, --max",
    },
    GeneratorInfo {
      name: "float",
      category: "web",
      description: "Random float",
      example: "3.14159",
      params: "--min, --max",
    },
    GeneratorInfo {
      name: "digit",
      category: "web",
      description: "Single digit (0-9)",
      example: "7",
      params: "",
    },
    // Composite types
    GeneratorInfo {
      name: "user",
      category: "composite",
      description: "User object (name, email, id)",
      example: "{name, email, id, created_at}",
      params: "",
    },
    GeneratorInfo {
      name: "address",
      category: "composite",
      description: "Address object",
      example: "{street, city, state, zip, country}",
      params: "",
    },
  ]
}
