/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare namespace MockResponse {
  /**
   * Create a binary response from a Buffer/ArrayBuffer.
   *
   * Sets `Content-Type: application/octet-stream` automatically.
   *
   * @param data - Binary data as Buffer.
   * @param init - Optional status code and headers.
   */
  export function arrayBuffer(data: Buffer, init?: JsResponseInit | undefined | null): JsHandlerResponse
  /**
   * Create an empty response with just a status code.
   *
   * @param status - HTTP status code.
   */
  export function empty(status: number): JsHandlerResponse
  /**
   * Create a network error response.
   *
   * When the interceptor sees this response, it throws a `TypeError("Failed to fetch")`
   * to simulate a network failure (DNS error, connection refused, etc.).
   */
  export function error(): JsHandlerResponse
  /**
   * Create an HTML response.
   *
   * Sets `Content-Type: text/html` automatically.
   *
   * @param body - HTML content.
   * @param init - Optional status code and headers.
   */
  export function html(body: string, init?: JsResponseInit | undefined | null): JsHandlerResponse
  /**
   * Create a JSON response.
   *
   * Sets `Content-Type: application/json` automatically.
   *
   * @param data - JSON value to serialize as the response body.
   * @param init - Optional status code and headers.
   */
  export function json(data: any, init?: JsResponseInit | undefined | null): JsHandlerResponse
  /**
   * Create a plain text response.
   *
   * Sets `Content-Type: text/plain` automatically.
   *
   * @param body - Text content.
   * @param init - Optional status code and headers.
   */
  export function text(body: string, init?: JsResponseInit | undefined | null): JsHandlerResponse
  /**
   * Create an XML response.
   *
   * Sets `Content-Type: application/xml` automatically.
   *
   * @param body - XML content.
   * @param init - Optional status code and headers.
   */
  export function xml(body: string, init?: JsResponseInit | undefined | null): JsHandlerResponse
}

/**
 * Internal holder for a handler-based MockDefinition.
 *
 * Created by `http.get()`, `http.post()`, etc. and consumed by `MockpitServer.useHandlers()`.
 */
export declare class JsHandler {
  /** Get the mock ID for this handler. */
  get id(): string | null
}

/**
 * Request context passed to handler functions.
 *
 * Fields are lazily converted to JS values on first access.
 * This avoids the overhead of constructing a full JS object with
 * all headers, query params, etc. for every request.
 */
export declare class MockpitRequest {
  /** Unique request identifier. */
  get requestId(): string
  get method(): string
  get path(): string
  get uri(): string
  get params(): Record<string, string>
  get query(): Record<string, string>
  get headers(): Record<string, string>
  get body(): string | null
  get bodyJson(): any | null
  /** Get a single param by name (faster than accessing the full params object). */
  param(name: string): string | null
  /** Get a single header by name (faster than accessing the full headers object). */
  header(name: string): string | null
  /** Get a single query param by name. */
  queryParam(name: string): string | null
  /** Parsed cookies from the Cookie request header. */
  get cookies(): Record<string, string>
}

/**
 * High-performance HTTP mock server.
 *
 * Supports both MSW-style handler functions and declarative YAML/JSON mocks.
 * All mocks (handler-based and declarative) live in the same registry with
 * the same priority and matching system.
 *
 * @example
 * ```ts
 * import { http, MockResponse, MockpitServer } from '@mockpit/node'
 *
 * const server = new MockpitServer()
 *
 * server.useHandlers([
 *   http.get('/api/users/:id', ({ params }) => {
 *     return MockResponse.json({ id: params.id, name: 'John' })
 *   }),
 * ])
 *
 * const url = await server.listen(3000)
 * // ... use the mock server ...
 * await server.close()
 * ```
 */
export declare class MockpitServer {
  /** Create a new mock server instance. */
  constructor()
  /**
   * Register handler-based mocks.
   *
   * Handlers are added to the same registry as declarative mocks.
   * They participate in the same priority-based matching system.
   *
   * @param handlers - Array of handlers created by `http.get()`, `http.post()`, etc.
   */
  useHandlers(handlers: Array<JsHandler>): void
  /**
   * Add runtime handlers (MSW's `server.use()`).
   *
   * Runtime handlers take priority over initial handlers (priority 200 vs 100).
   * They are added to the same registry and participate in matching.
   *
   * @param handlers - Array of handlers created by `http.get()`, `http.post()`, etc.
   */
  use(handlers: Array<JsHandler>): void
  /**
   * Re-enable consumed one-time handlers (MSW's `server.restoreHandlers()`).
   *
   * One-time handlers (`{ once: true }`) are disabled after first match.
   * This method re-enables them so they can match again.
   */
  restoreHandlers(): void
  /**
   * Remove all handler-based mocks (those with IDs starting with "handler:").
   *
   * Declarative mocks loaded from files are not affected.
   */
  resetHandlers(): void
  /**
   * Load declarative mocks from a directory containing YAML/JSON/HAR files.
   *
   * @param dirPath - Path to a directory containing mock definition files.
   * @returns Number of mocks loaded.
   */
  loadMocks(dirPath: string): Promise<number>
  /**
   * Load mocks from a single file (YAML, JSON, or HAR).
   *
   * @param filePath - Path to a .yaml, .yml, .json, or .har file.
   * @returns Number of mocks loaded.
   */
  loadMockFile(filePath: string): Promise<number>
  /**
   * Add a single mock from a JSON configuration object.
   *
   * @param config - Mock configuration as JSON (same format as YAML mock files).
   * @returns The mock ID.
   */
  addMock(config: any): Promise<string>
  /**
   * Remove a mock by ID.
   *
   * @param id - The mock ID to remove.
   * @returns `true` if the mock was found and removed.
   */
  removeMock(id: string): boolean
  /** Get the number of registered mocks. */
  get mockCount(): number
  /**
   * List all registered handlers.
   *
   * Returns an array of handler info objects with id and method/path info.
   * Equivalent to MSW's `server.listHandlers()`.
   */
  listHandlers(): Array<HandlerInfo>
  /**
   * Start the mock server on the given port.
   *
   * @param port - Port number (default: 0 for random available port).
   * @returns The URL the server is listening on (e.g., `http://127.0.0.1:3000`).
   */
  listen(port?: number | undefined | null): Promise<string>
  /** Stop the mock server. */
  close(): Promise<void>
  /** Check if the server is running. */
  get isRunning(): boolean
  /** Get the port the server is listening on. */
  get port(): number | null
  /**
   * Match a request against the mock registry and generate the response.
   *
   * **Optimization**: For handler mocks, uses `FunctionRef` to call the JS
   * handler directly from the deferred resolver callback (JS thread).
   * This eliminates the ~22us TSFN queue+wakeup overhead, replacing it with
   * a direct `napi_call_function` (~1us).
   *
   * Flow:
   * 1. Rust matching on tokio (~12us)
   * 2. Deferred resolver on JS thread:
   *    - Declarative: response already built
   *    - Handler: FunctionRef direct call (~1us)
   *
   * Returns null if no mock matches.
   */
  matchRequest(method: string, path: string, query?: string | undefined | null, headers?: Record<string, string> | undefined | null, body?: string | undefined | null): Promise<MaybePromise>
}

/**
 * Auto-discover a mockpit config file in the given directory.
 * Returns the path if found, null otherwise.
 */
export declare function discoverConfigFile(dir?: string | undefined | null): string | null

/** Handler info returned by `listHandlers()`. */
export interface HandlerInfo {
  id: string
  methods: Array<string>
  enabled: boolean
}

/**
 * Response returned from JS handler functions.
 *
 * Return `null`/`undefined` from a handler to signal passthrough.
 */
export interface JsHandlerResponse {
  /** HTTP status code (default: 200) */
  status?: number
  /** Response headers */
  headers?: Record<string, string>
  /** Response body as string */
  body?: string
  /** Response body as JSON (takes precedence over `body` if both set) */
  bodyJson?: any
}

/**
 * Request context passed to JS handler functions.
 *
 * Contains all HTTP request information plus captured path parameters.
 */
export interface JsRequestContext {
  /** HTTP method (GET, POST, etc.) */
  method: string
  /** Full URI including query string */
  uri: string
  /** Request path (without query string) */
  path: string
  /** Path parameter captures from `:param` patterns */
  params: Record<string, string>
  /** Parsed query parameters */
  query: Record<string, string>
  /** Request headers */
  headers: Record<string, string>
  /** Request body as string (if UTF-8) */
  body?: string
  /** Request body parsed as JSON (if valid JSON) */
  bodyJson?: any
}

/** Options for response construction. */
export interface JsResponseInit {
  /** HTTP status code */
  status?: number
  /** Response headers */
  headers?: Record<string, string>
}

/** Result of matching a request against the mock registry. */
export interface MatchedResponse {
  status: number
  headers: Record<string, string>
  body: string
  mockId: string
}

/** Parse a mockpit config file (YAML or JSON). Detects format from extension. */
export declare function parseConfigFile(filePath: string): any

/** Parse a mockpit config from a string with explicit format ("yaml", "json"). */
export declare function parseConfigString(content: string, format: string): any

export declare namespace fake {
  export function alphanumeric(length?: number | undefined | null): string
  export function amount(): string
  export function apiEndpoint(): string
  export function apiUrl(): string
  export function apiVersion(): string
  export function base64Data(): string
  export function boolean(): boolean
  export function buildingNumber(): string
  export function cellPhone(): string
  export function city(): string
  export function color(): string
  export function company(): string
  export function companySuffix(): string
  export function country(): string
  export function countryCode(): string
  export function creditCard(): string
  export function currencyCode(): string
  export function currencyName(): string
  export function currencySymbol(): string
  export function date(): string
  export function digit(): number
  export function domain(): string
  export function downloadUrl(): string
  export function email(): string
  export function etag(): string
  export function fileDownloadUrl(): string
  export function fileExtension(): string
  export function filename(): string
  export function fileSize(min?: number | undefined | null, max?: number | undefined | null): number
  export function firstName(): string
  export function float(min?: number | undefined | null, max?: number | undefined | null): number
  export function freeEmail(): string
  export function hexColor(): string
  export function industry(): string
  export function ipv4(): string
  export function ipv6(): string
  export function isbn(): string
  export function isbn13(): string
  export function isoDate(): string
  export function jobField(): string
  export function jobPosition(): string
  export function jobSeniority(): string
  export function jobTitle(): string
  export function jwt(): string
  export function lastName(): string
  export function latitude(): string
  export function locale(): string
  export function longitude(): string
  export function macAddress(): string
  export function md5(): string
  export function mimeType(): string
  export function name(): string
  export function number(min?: number | undefined | null, max?: number | undefined | null): number
  export function numericId(): string
  export function paginationUrl(): string
  export function paginationUrlOffset(): string
  export function paragraph(sentenceCount?: number | undefined | null): string
  export function password(): string
  export function phone(): string
  export function postalCode(): string
  export function price(min?: number | undefined | null, max?: number | undefined | null): number
  export function relativeTime(): string
  export function resourcePath(): string
  export function rgbColor(): string
  export function searchUrl(): string
  export function secondaryAddress(): string
  export function semver(): string
  export function semverPrerelease(): string
  export function sentence(wordCount?: number | undefined | null): string
  export function sha256(): string
  export function shortHash(): string
  export function slug(): string
  export function state(): string
  export function stateAbbr(): string
  export function statusMessage(): string
  export function street(): string
  export function streetAddress(): string
  export function suffix(): string
  export function time(): string
  export function timezone(): string
  export function title(): string
  export function token(): string
  export function unixTimestamp(): number
  export function url(): string
  export function userAgent(): string
  export function userAgentModern(): string
  export function username(): string
  export function uuid(): string
  export function version(): string
  export function webhookUrl(): string
  export function word(): string
  export function words(count?: number | undefined | null): string
  export function zip(): string
}

export declare namespace graphql {
  /**
   * Create a handler mock for a GraphQL mutation operation.
   *
   * @param operationName - The GraphQL operation name to match.
   * @param handler - Async function receiving request context, returning response or null.
   */
  export function mutation(operationName: string, handlerFn: (arg: MockpitRequest) => Promise<JsHandlerResponse | undefined | null>): JsHandler
  /**
   * Create a handler mock matching any GraphQL operation.
   *
   * @param handler - Async function receiving request context, returning response or null.
   */
  export function operation(handlerFn: (arg: MockpitRequest) => Promise<JsHandlerResponse | undefined | null>): JsHandler
  /**
   * Create a handler mock for a GraphQL query operation.
   *
   * @param operationName - The GraphQL operation name to match (e.g., `"GetUser"`).
   * @param handler - Async function receiving request context, returning response or null.
   */
  export function query(operationName: string, handlerFn: (arg: MockpitRequest) => Promise<JsHandlerResponse | undefined | null>): JsHandler
}

export declare namespace http {
  /** Create a handler mock matching any HTTP method. */
  export function all(path: unknown, handlerFn: (arg: MockpitRequest) => Promise<JsHandlerResponse | undefined | null>): JsHandler
  /** Create a DELETE handler mock. */
  export function delete(path: unknown, handlerFn: (arg: MockpitRequest) => Promise<JsHandlerResponse | undefined | null>): JsHandler
  /**
   * Create a GET handler mock.
   *
   * @param path - URL pattern string (e.g., `/users/:id`) or RegExp.
   * @param handler - Async function receiving request context, returning response or null.
   */
  export function get(path: unknown, handlerFn: (arg: MockpitRequest) => Promise<JsHandlerResponse | undefined | null>): JsHandler
  /** Create a HEAD handler mock. */
  export function head(path: unknown, handlerFn: (arg: MockpitRequest) => Promise<JsHandlerResponse | undefined | null>): JsHandler
  /** Create an OPTIONS handler mock. */
  export function options(path: unknown, handlerFn: (arg: MockpitRequest) => Promise<JsHandlerResponse | undefined | null>): JsHandler
  /** Create a PATCH handler mock. */
  export function patch(path: unknown, handlerFn: (arg: MockpitRequest) => Promise<JsHandlerResponse | undefined | null>): JsHandler
  /** Create a POST handler mock. */
  export function post(path: unknown, handlerFn: (arg: MockpitRequest) => Promise<JsHandlerResponse | undefined | null>): JsHandler
  /** Create a PUT handler mock. */
  export function put(path: unknown, handlerFn: (arg: MockpitRequest) => Promise<JsHandlerResponse | undefined | null>): JsHandler
}

export declare namespace services {
  export function consolidate(input: JsConsolidateInput): Promise<JsConsolidateResult>
  export function convert(input: JsConvertInput): Promise<JsConvertResult>
  export function create(input: JsCreateInput): JsCreateResult
  export function exportHar(input: JsExportInput): Promise<JsExportResult>
  export function fakeData(input: JsFakeDataInput): Array<string>
  export function fakeImage(input: JsFakeImageInput): JsFakeImageResult
  export function fakePdf(input: JsFakePdfInput): JsFakePdfResult
  export function format(input: JsFormatInput): JsFormatOutput
  export function formatContent(content: string, fileFormat: string): string
  export interface JsConsolidateInput {
    input: string
    format?: string
    minPattern?: number
    enableTemplates?: boolean
  }
  export interface JsConsolidateResult {
    content: string
    mocksBefore: number
    mocksAfter: number
    inputSize: number
    outputSize: number
  }
  export interface JsConvertInput {
    input: string
    format?: string
    excludePreflight?: boolean
    excludeRedirects?: boolean
    stripBrowserHeaders?: boolean
    normalizeUrls?: boolean
    allowedDomains?: Array<string>
    excludeStaticAssets?: boolean
    stripSensitiveHeaders?: boolean
    stripInfrastructureHeaders?: boolean
  }
  export interface JsConvertResult {
    entriesProcessed: number
    mocksCount: number
    content: string
  }
  export interface JsCreateInput {
    url: string
    method?: string
    status?: number
    body?: string
    template?: boolean
    id?: string
    priority?: number
    collection?: string
    format?: string
  }
  export interface JsCreateResult {
    mockId: string
    content: string
  }
  export interface JsExportInput {
    mocksDir?: string
    filter?: string
  }
  export interface JsExportResult {
    content: string
    mocksExported: number
  }
  export interface JsFakeDataInput {
    generator: string
    count?: number
    min?: number
    max?: number
    words?: number
    length?: number
  }
  export interface JsFakeImageInput {
    imageType?: string
    width?: number
    height?: number
    bgColor?: string
    textColor?: string
    text?: string
    initials?: string
    startColor?: string
    endColor?: string
    direction?: string
    imageFormat?: string
    quality?: number
    colored?: boolean
  }
  export interface JsFakeImageResult {
    base64: string
    mimeType: string
  }
  export interface JsFakePdfInput {
    pages?: number
    text?: string
  }
  export interface JsFakePdfResult {
    base64: string
  }
  export interface JsFormatFileResult {
    path: string
    changed: boolean
    error?: string
  }
  export interface JsFormatInput {
    path: string
    check?: boolean
  }
  export interface JsFormatOutput {
    files: Array<JsFormatFileResult>
    formattedCount: number
    errorCount: number
    unchangedCount: number
  }
  export interface JsGeneratorInfo {
    name: string
    category: string
    description: string
    example: string
  }
  export interface JsListInput {
    mocksDir?: string
    filter?: string
  }
  export interface JsListOutput {
    mocks: Array<JsMockSummary>
    total: number
  }
  export interface JsMockSummary {
    id: string
    priority: number
    enabled: boolean
    methods: Array<string>
    urlPatterns: Array<string>
    status: number
    hasHeaderMatchers: boolean
    hasDelay: boolean
    scope?: string
  }
  export interface JsServeInput {
    port?: number
    host?: string
    mocksDir?: string
    mockFile?: string
    watch?: boolean
    cors?: boolean
    verbose?: boolean
  }
  export interface JsServeResult {
    port: number
    url: string
  }
  export interface JsTemplateInput {
    template: string
    context?: any
    count?: number
  }
  export interface JsTestMatchInput {
    method: string
    path: string
    query?: string
    headers?: Record<string, string>
    body?: string
    render?: boolean
    mocksDir?: string
    mockFile?: string
  }
  export interface JsValidateContentInput {
    content: string
    fileFormat: string
  }
  export interface JsValidateInput {
    path: string
  }
  export interface JsValidateOutput {
    isValid: boolean
    totalErrors: number
    totalWarnings: number
    errors: Array<JsValidationError>
    warnings: Array<JsValidationError>
  }
  export interface JsValidationError {
    mockId?: string
    message: string
    errorType: string
    lineNumber?: number
    suggestion?: string
  }
  export function list(input: JsListInput): Promise<JsListOutput>
  export function listGenerators(category?: string | undefined | null, search?: string | undefined | null): Array<JsGeneratorInfo>
  export function renderTemplate(input: JsTemplateInput): Array<string>
  /**
   * Start a standalone mock server using the service layer.
   *
   * Returns the URL and port. The server runs until the process exits.
   * For more control (stop/restart), use the MockpitServer class instead.
   */
  export function serve(input: JsServeInput): Promise<JsServeResult>
  export function show(mockId: string, mocksDir?: string | undefined | null): Promise<any | null>
  export function testMatch(input: JsTestMatchInput): Promise<any>
  export function validate(input: JsValidateInput): Promise<JsValidateOutput>
  export function validateContent(input: JsValidateContentInput): Promise<JsValidateOutput>
}
