/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare namespace HttpResponse {
  /**
   * Create a binary response from a Buffer/ArrayBuffer.
   *
   * Sets `Content-Type: application/octet-stream` automatically.
   * Binary-safe: bytes pass through untouched.
   */
  export function arrayBuffer(data: Uint8Array, init?: HandlerResponseInit | undefined | null): HandlerResponse
  /**
   * Create a network error response.
   *
   * When the interceptor sees this response, it throws a `TypeError("Failed to fetch")`
   * to simulate a network failure (DNS error, connection refused, etc.).
   */
  export function error(): HandlerResponse
  /**
   * Create an HTML response.
   *
   * Sets `Content-Type: text/html` automatically.
   */
  export function html(body: string, init?: HandlerResponseInit | undefined | null): HandlerResponse
  /**
   * Create a JSON response.
   *
   * Sets `Content-Type: application/json` automatically.
   *
   * @param data - JSON value to serialize as the response body.
   * @param init - Optional status code, status text, and headers.
   */
  export function json(data: any, init?: HandlerResponseInit | undefined | null): HandlerResponse
  /** Create a redirect response (default 302) with a Location header. */
  export function redirect(url: string, status?: number | undefined | null): HandlerResponse
  /**
   * Create a plain text response.
   *
   * Sets `Content-Type: text/plain` automatically.
   */
  export function text(body: string, init?: HandlerResponseInit | undefined | null): HandlerResponse
  /**
   * Create an XML response.
   *
   * Sets `Content-Type: text/xml` automatically (matches MSW).
   */
  export function xml(body: string, init?: HandlerResponseInit | undefined | null): HandlerResponse
}

/**
 * High-performance HTTP mock server.
 *
 * Supports both MSW-style handler functions and declarative YAML/JSON mocks.
 * All mocks (handler-based and declarative) live in the same registry with
 * the same priority and matching system.
 *
 * @example
 * ```ts
 * import { http, HttpResponse, FerrimockServer } from 'ferrimock-node'
 *
 * const server = new FerrimockServer()
 *
 * server.useHandlers([
 *   http.get('/api/users/:id', ({ params }) => {
 *     return HttpResponse.json({ id: params.id, name: 'John' })
 *   }),
 * ])
 *
 * const url = await server.listen(3000)
 * // ... use the mock server ...
 * await server.close()
 * ```
 */
export declare class FerrimockServer {
  /** Create a new mock server instance. */
  constructor()
  /**
   * Register handler-based mocks.
   *
   * Handlers are added to the same registry as declarative mocks.
   * They participate in the same priority-based matching system.
   *
   * @param handlers - Array of handlers created by `http.get()`, `http.post()`, etc.
   */
  useHandlers(handlers: Array<RequestHandler>): void
  /**
   * Add runtime handlers (MSW's `server.use()`).
   *
   * Runtime handlers take priority over initial handlers (priority 200 vs 100)
   * and are scoped so `resetRuntimeHandlers()` removes only them.
   *
   * @param handlers - Array of handlers created by `http.get()`, `http.post()`, etc.
   */
  use(handlers: Array<RequestHandler>): void
  /**
   * Re-enable consumed one-time handlers (MSW's `server.restoreHandlers()`).
   *
   * One-time handlers (`{ once: true }`) are disabled after first match.
   * This method re-enables them so they can match again.
   */
  restoreHandlers(): void
  /**
   * MSW's `server.resetHandlers()`: remove runtime handlers added via
   * `use()` and restore initial handlers (re-enabling consumed one-time
   * handlers). Handlers registered via `useHandlers()` stay.
   */
  resetRuntimeHandlers(): void
  /**
   * Remove ALL handler-based mocks (initial and runtime). Used by
   * MSW's `server.resetHandlers(...nextHandlers)` overload, which
   * replaces the initial set. Declarative mocks loaded from files are
   * not affected.
   */
  resetHandlers(): void
  /**
   * Load declarative mocks from a directory containing YAML/JSON/HAR files.
   *
   * @param dirPath - Path to a directory containing mock definition files.
   * @returns Number of mocks loaded.
   */
  loadMocks(dirPath: string): Promise<number>
  /**
   * Load mocks from a single file (YAML, JSON, or HAR).
   *
   * @param filePath - Path to a .yaml, .yml, .json, or .har file.
   * @returns Number of mocks loaded.
   */
  loadMockFile(filePath: string): Promise<number>
  /**
   * Add a single mock from a JSON configuration object.
   *
   * @param config - Mock configuration as JSON (same format as YAML mock files).
   * @returns The mock ID.
   */
  addMock(config: any): Promise<string>
  /**
   * Remove a mock by ID.
   *
   * @param id - The mock ID to remove.
   * @returns `true` if the mock was found and removed.
   */
  removeMock(id: string): boolean
  /** Get the number of registered mocks. */
  get mockCount(): number
  /**
   * Whether any registered mock matches on the request body (body or GraphQL
   * matcher). Lets the interceptor skip reading the request body when no mock
   * could use it.
   */
  get needsRequestBody(): boolean
  /**
   * Whether any registered mock needs request headers (header matchers,
   * handler mocks, or header-referencing templates). The interceptor
   * skips marshalling headers when false.
   */
  get needsRequestHeaders(): boolean
  /**
   * List all registered handlers.
   *
   * Returns an array of handler info objects with id, method/path info,
   * and MSW's display strings: `pattern` is the predicate as the user
   * wrote it and `header` is MSW's `info.header` ("GET /users/:id",
   * "query GetUser (origin: *)"). Equivalent to MSW's
   * `server.listHandlers()`. WebSocket mocks carry `kind: "websocket"`
   * (MSW's WebSocketHandler tag).
   */
  listHandlers(): Array<HandlerInfo>
  /**
   * Every WebSocket mock matching a connection handshake, in
   * precedence order — the interceptor lane dispatches an intercepted
   * connection to ALL matching `ws` handlers (MSW semantics). No side
   * effects (no `once` consumption, no call tracking).
   *
   * @param url - The connection URL (`wss://host/path`).
   */
  matchWsConnections(url: string): Array<WsConnectionMatch>
  /**
   * Start the mock server on the given port.
   *
   * @param port - Port number (default: 0 for random available port).
   * @returns The URL the server is listening on (e.g., `http://127.0.0.1:3000`).
   */
  listen(port?: number | undefined | null): Promise<string>
  /** Stop the mock server. */
  close(): Promise<void>
  /** Check if the server is running. */
  get isRunning(): boolean
  /** Get the port the server is listening on. */
  get port(): number | null
  /**
   * Match a request against the mock registry and generate the response.
   *
   * **Optimization**: For handler mocks, uses `FunctionRef` to call the JS
   * handler directly from the deferred resolver callback (JS thread).
   * This eliminates the ~22us TSFN queue+wakeup overhead, replacing it with
   * a direct `napi_call_function` (~1us).
   *
   * Flow:
   * 1. Rust matching on tokio (~12us)
   * 2. Deferred resolver on JS thread:
   *    - Declarative: response already built
   *    - Handler: FunctionRef direct call (~1us)
   *
   * Returns null if no mock matches. When a handler falls through
   * (returns null/undefined), resolves with `{ fallthrough: true,
   * mockId }` — re-call with that ID added to `excludeIds` to try the
   * next candidate (MSW semantics; the JS interceptor loops).
   */
  matchRequest(method: string, path: string, query?: string | undefined | null, headers?: Record<string, string> | undefined | null, body?: string | Uint8Array | undefined | null, requestId?: string | undefined | null, excludeIds?: Array<string> | undefined | null): Promise<MatchedResponse | null>
}

/**
 * GraphQL resolver info (MSW's `{ query, variables, operationName,
 * cookies, request, requestId }`).
 */
export declare class GraphQlRequestInfo {
  /** Unique request identifier. */
  get requestId(): string
  /** The GraphQL document string. */
  get query(): string | null
  get variables(): any
  /**
   * Explicit operationName field, falling back to the name declared in
   * the query document.
   */
  get operationName(): string | null
  /** A real Fetch API `Request` for this request (MSW's `info.request`). */
  get request(): Request
  /** Parsed cookies from the Cookie request header. */
  get cookies(): Record<string, string>
}
export type GraphQLRequestInfo = GraphQlRequestInfo

/**
 * Internal holder for a handler-based MockDefinition.
 *
 * Created by `http.get()`, `http.post()`, etc. and consumed by `FerrimockServer.useHandlers()`.
 */
export declare class RequestHandler {
  /** Get the mock ID for this handler. */
  get id(): string | null
  /** The predicate as the user wrote it (path string or RegExp display). */
  get pattern(): string | null
}

/**
 * HTTP resolver info: MSW's `{ request, params, cookies, requestId }`.
 *
 * Fields are lazily converted to JS values on first access.
 */
export declare class RequestInfo {
  /** Unique request identifier. */
  get requestId(): string
  /**
   * A real Fetch API `Request` for this request (MSW's `info.request`).
   * Built on access; destructure it once per handler call.
   */
  get request(): Request
  /**
   * Path parameters captured from the URL pattern. Repeatable params
   * (`:name+` / `:name*`) surface as arrays (MSW semantics).
   */
  get params(): Record<string, string | Array<string>>
  /** Parsed cookies from the Cookie request header. */
  get cookies(): Record<string, string>
}

/** The live connection sink handed to TCP-lane resolvers. */
export declare class SseClientHandle {
  /** Send a message; sends after close are silent no-ops. */
  send(payload: SseMessagePayload): void
  /** End the stream cleanly. */
  close(): void
  /** Abort the connection (the consumer sees a network error). */
  error(): void
}

/**
 * The intercepted client half of a live TCP-lane connection: sends go
 * straight into the server socket pump.
 */
export declare class WebSocketClientHandle {
  get id(): string
  get url(): string
  /** Send text (string) or binary (Uint8Array) to the client. */
  send(data: string | Uint8Array): void
  close(code?: number | undefined | null, reason?: string | undefined | null): void
}

/**
 * The real upstream half of a live TCP-lane connection, idle until
 * `connect()` is called.
 */
export declare class WebSocketServerHandle {
  /**
   * Dial the real server (the link's absolute ws(s):// URL) and
   * start forwarding.
   */
  connect(): void
  /** Send to the real server. */
  send(data: string | Uint8Array): void
  close(): void
}

/**
 * Auto-discover a ferrimock config file in the given directory.
 * Returns the path if found, null otherwise.
 */
export declare function discoverConfigFile(dir?: string | undefined | null): string | null

/** Handler info returned by `listHandlers()`. */
export interface HandlerInfo {
  id: string
  methods: Array<string>
  enabled: boolean
  /** `"websocket"` for WebSocket mocks (MSW's handler tag), absent otherwise. */
  kind?: string
  /**
   * The predicate as the user wrote it (`/users/:id`, a full URL, a
   * RegExp display form, or a single exact URL for declarative mocks).
   */
  pattern?: string
  /**
   * MSW's `info.header` display ("GET /users/:id",
   * "query GetUser (origin: *)").
   */
  header?: string
}

/**
 * Response returned from JS handler functions.
 *
 * Return `null`/`undefined` from a handler to fall through to the next
 * matching mock (MSW semantics).
 */
export interface HandlerResponse {
  /** HTTP status code (default: 200) */
  status?: number
  /** Custom status text (Node interceptor only; HTTP/2 has no reason phrases) */
  statusText?: string
  /** Response headers */
  headers?: Record<string, string>
  /** Response body as string */
  body?: string
  /** Response body as JSON (takes precedence over `body` if both set) */
  bodyJson?: any
  /**
   * Raw binary response body (takes precedence over `body`/`body_json`).
   * Set by `HttpResponse.arrayBuffer()` for binary-safe responses.
   */
  bodyBytes?: Uint8Array
}

/** Options for response construction. */
export interface HandlerResponseInit {
  /** HTTP status code */
  status?: number
  /** Custom status text */
  statusText?: string
  /** Response headers */
  headers?: Record<string, string>
}

/**
 * Result of matching a request against the mock registry.
 *
 * `body` is raw bytes (`Uint8Array`) so binary responses (images, protobuf,
 * gzip) round-trip losslessly. Build a `Response` directly from it; decode with
 * `TextDecoder` when a string is needed.
 */
export interface MatchedResponse {
  status: number
  /** Custom status text from the handler (Node interceptor applies it). */
  statusText?: string
  headers: Record<string, string>
  body: Uint8Array
  mockId: string
  /**
   * Set when a handler returned null/undefined: re-match with this
   * mock's ID excluded (MSW fall-through).
   */
  fallthrough?: boolean
}

/** Parse a ferrimock config file (YAML or JSON). Detects format from extension. */
export declare function parseConfigFile(filePath: string): any

/** Parse a ferrimock config from a string with explicit format ("yaml", "json"). */
export declare function parseConfigString(content: string, format: string): any

/** Handler registration options (MSW's third argument). */
export interface RequestHandlerOptions {
  /** Deactivate the handler after its first successful response. */
  once?: boolean
}

/**
 * Create a Server-Sent Events handler mock.
 *
 * @param path - URL pattern string (`/stream`, absolute URL) or RegExp.
 * @param handler - Resolver receiving `(info, client?)`: with a native
 *   `client` (TCP lane) it drives the sink; without one (interceptor
 *   lane) it returns a `text/event-stream` Response.
 * @param options - Optional `{ once: true }` for one-time handlers.
 */
export declare function sse(path: unknown, handlerFn: (arg: RequestInfo) => Promise<HandlerResponse | undefined | null>, options?: RequestHandlerOptions | undefined | null): RequestHandler

/**
 * One outbound SSE message: `data` objects are JSON-stringified (MSW
 * semantics), strings pass through verbatim.
 */
export interface SseMessagePayload {
  id?: string
  event?: string
  data?: any
  retry?: number
}

/** One WebSocket mock matched by `matchWsConnections`. */
export interface WsConnectionMatch {
  mockId: string
  params: Record<string, string | Array<string>>
}

export declare namespace fake {
  export function alphanumeric(length?: number | undefined | null): string
  export function amount(): string
  export function apiEndpoint(): string
  export function apiUrl(): string
  export function apiVersion(): string
  export function base64Data(): string
  export function boolean(): boolean
  export function buildingNumber(): string
  export function cellPhone(): string
  export function city(): string
  export function color(): string
  export function company(): string
  export function companySuffix(): string
  export function country(): string
  export function countryCode(): string
  export function creditCard(): string
  export function currencyCode(): string
  export function currencyName(): string
  export function currencySymbol(): string
  export function date(): string
  export function digit(): number
  export function domain(): string
  export function downloadUrl(): string
  export function email(): string
  export function etag(): string
  export function fileDownloadUrl(): string
  export function fileExtension(): string
  export function filename(): string
  export function fileSize(min?: number | undefined | null, max?: number | undefined | null): number
  export function firstName(): string
  export function float(min?: number | undefined | null, max?: number | undefined | null): number
  export function freeEmail(): string
  export function hexColor(): string
  export function industry(): string
  export function ipv4(): string
  export function ipv6(): string
  export function isbn(): string
  export function isbn13(): string
  export function isoDate(): string
  export function jobField(): string
  export function jobPosition(): string
  export function jobSeniority(): string
  export function jobTitle(): string
  export function jwt(): string
  export function lastName(): string
  export function latitude(): string
  export function locale(): string
  export function longitude(): string
  export function macAddress(): string
  export function md5(): string
  export function mimeType(): string
  export function name(): string
  export function number(min?: number | undefined | null, max?: number | undefined | null): number
  export function numericId(): string
  export function paginationUrl(): string
  export function paginationUrlOffset(): string
  export function paragraph(sentenceCount?: number | undefined | null): string
  export function password(): string
  export function phone(): string
  export function postalCode(): string
  export function price(min?: number | undefined | null, max?: number | undefined | null): number
  export function relativeTime(): string
  export function resourcePath(): string
  export function rgbColor(): string
  export function searchUrl(): string
  export function secondaryAddress(): string
  export function semver(): string
  export function semverPrerelease(): string
  export function sentence(wordCount?: number | undefined | null): string
  export function sha256(): string
  export function shortHash(): string
  export function slug(): string
  export function state(): string
  export function stateAbbr(): string
  export function statusMessage(): string
  export function street(): string
  export function streetAddress(): string
  export function suffix(): string
  export function time(): string
  export function timezone(): string
  export function title(): string
  export function token(): string
  export function unixTimestamp(): number
  export function url(): string
  export function userAgent(): string
  export function userAgentModern(): string
  export function username(): string
  export function uuid(): string
  export function version(): string
  export function webhookUrl(): string
  export function word(): string
  export function words(count?: number | undefined | null): string
  export function zip(): string
}

export declare namespace graphql {
  /**
   * Create a handler mock for a GraphQL mutation operation.
   *
   * @param operationName - Operation name to match: string or RegExp.
   * @param handler - Function receiving GraphQL resolver info, returning a response,
   *   or null/undefined to fall through.
   * @param options - Optional `{ once: true }`.
   * @param endpoint - Optional endpoint URL scope (used by `graphql.link`).
   */
  export function mutation(operationName: unknown, handlerFn: (arg: GraphQLRequestInfo) => Promise<HandlerResponse | undefined | null>, options?: RequestHandlerOptions | undefined | null, endpoint?: string | undefined | null): RequestHandler
  /**
   * Create a handler mock matching any GraphQL operation.
   *
   * @param handler - Function receiving GraphQL resolver info, returning a response,
   *   or null/undefined to fall through.
   * @param options - Optional `{ once: true }`.
   * @param endpoint - Optional endpoint URL scope (used by `graphql.link`).
   */
  export function operation(handlerFn: (arg: GraphQLRequestInfo) => Promise<HandlerResponse | undefined | null>, options?: RequestHandlerOptions | undefined | null, endpoint?: string | undefined | null): RequestHandler
  /**
   * Create a handler mock for a GraphQL query operation.
   *
   * @param operationName - Operation name to match: string or RegExp.
   * @param handler - Function receiving GraphQL resolver info, returning a response,
   *   or null/undefined to fall through.
   * @param options - Optional `{ once: true }`.
   * @param endpoint - Optional endpoint URL scope (used by `graphql.link`).
   */
  export function query(operationName: unknown, handlerFn: (arg: GraphQLRequestInfo) => Promise<HandlerResponse | undefined | null>, options?: RequestHandlerOptions | undefined | null, endpoint?: string | undefined | null): RequestHandler
}

export declare namespace http {
  /**
   * Create a handler mock matching any HTTP method.
   *
   *  @param path - URL pattern string (`/users/:id`, full URL) or RegExp.
   *  @param handler - Function receiving the resolver info, returning a response,
   *    or null/undefined to fall through to the next matching mock.
   *  @param options - Optional `{ once: true }` for one-time handlers.
   */
  export function all(path: unknown, handlerFn: (arg: RequestInfo) => Promise<HandlerResponse | undefined | null>, options?: RequestHandlerOptions | undefined | null): RequestHandler
  /**
   * Create a DELETE handler mock.
   *
   * @param path - URL pattern string (`/users/:id`, full URL) or RegExp.
   * @param handler - Function receiving the resolver info, returning a response,
   *   or null/undefined to fall through to the next matching mock.
   * @param options - Optional `{ once: true }` for one-time handlers.
   */
  export function delete(path: unknown, handlerFn: (arg: RequestInfo) => Promise<HandlerResponse | undefined | null>, options?: RequestHandlerOptions | undefined | null): RequestHandler
  /**
   * Create a GET handler mock.
   *
   *  @param path - URL pattern string (`/users/:id`, full URL) or RegExp.
   *  @param handler - Function receiving the resolver info, returning a response,
   *    or null/undefined to fall through to the next matching mock.
   *  @param options - Optional `{ once: true }` for one-time handlers.
   */
  export function get(path: unknown, handlerFn: (arg: RequestInfo) => Promise<HandlerResponse | undefined | null>, options?: RequestHandlerOptions | undefined | null): RequestHandler
  /**
   * Create a HEAD handler mock.
   *
   *  @param path - URL pattern string (`/users/:id`, full URL) or RegExp.
   *  @param handler - Function receiving the resolver info, returning a response,
   *    or null/undefined to fall through to the next matching mock.
   *  @param options - Optional `{ once: true }` for one-time handlers.
   */
  export function head(path: unknown, handlerFn: (arg: RequestInfo) => Promise<HandlerResponse | undefined | null>, options?: RequestHandlerOptions | undefined | null): RequestHandler
  /**
   * Create an OPTIONS handler mock.
   *
   *  @param path - URL pattern string (`/users/:id`, full URL) or RegExp.
   *  @param handler - Function receiving the resolver info, returning a response,
   *    or null/undefined to fall through to the next matching mock.
   *  @param options - Optional `{ once: true }` for one-time handlers.
   */
  export function options(path: unknown, handlerFn: (arg: RequestInfo) => Promise<HandlerResponse | undefined | null>, options?: RequestHandlerOptions | undefined | null): RequestHandler
  /**
   * Create a PATCH handler mock.
   *
   *  @param path - URL pattern string (`/users/:id`, full URL) or RegExp.
   *  @param handler - Function receiving the resolver info, returning a response,
   *    or null/undefined to fall through to the next matching mock.
   *  @param options - Optional `{ once: true }` for one-time handlers.
   */
  export function patch(path: unknown, handlerFn: (arg: RequestInfo) => Promise<HandlerResponse | undefined | null>, options?: RequestHandlerOptions | undefined | null): RequestHandler
  /**
   * Create a POST handler mock.
   *
   *  @param path - URL pattern string (`/users/:id`, full URL) or RegExp.
   *  @param handler - Function receiving the resolver info, returning a response,
   *    or null/undefined to fall through to the next matching mock.
   *  @param options - Optional `{ once: true }` for one-time handlers.
   */
  export function post(path: unknown, handlerFn: (arg: RequestInfo) => Promise<HandlerResponse | undefined | null>, options?: RequestHandlerOptions | undefined | null): RequestHandler
  /**
   * Create a PUT handler mock.
   *
   *  @param path - URL pattern string (`/users/:id`, full URL) or RegExp.
   *  @param handler - Function receiving the resolver info, returning a response,
   *    or null/undefined to fall through to the next matching mock.
   *  @param options - Optional `{ once: true }` for one-time handlers.
   */
  export function put(path: unknown, handlerFn: (arg: RequestInfo) => Promise<HandlerResponse | undefined | null>, options?: RequestHandlerOptions | undefined | null): RequestHandler
}

export declare namespace services {
  export function consolidate(input: JsConsolidateInput): Promise<JsConsolidateResult>
  export function convert(input: JsConvertInput): Promise<JsConvertResult>
  export function create(input: JsCreateInput): JsCreateResult
  export function exportHar(input: JsExportInput): Promise<JsExportResult>
  export function fakeData(input: JsFakeDataInput): Array<string>
  export function fakeImage(input: JsFakeImageInput): JsFakeImageResult
  export function fakePdf(input: JsFakePdfInput): JsFakePdfResult
  export function format(input: JsFormatInput): JsFormatOutput
  export function formatContent(content: string, fileFormat: string): string
  export interface JsConsolidateInput {
    input: string
    format?: string
    minPattern?: number
    enableTemplates?: boolean
  }
  export interface JsConsolidateResult {
    content: string
    mocksBefore: number
    mocksAfter: number
    inputSize: number
    outputSize: number
  }
  export interface JsConvertInput {
    input: string
    format?: string
    excludePreflight?: boolean
    excludeRedirects?: boolean
    stripBrowserHeaders?: boolean
    normalizeUrls?: boolean
    allowedDomains?: Array<string>
    excludeStaticAssets?: boolean
    stripSensitiveHeaders?: boolean
    stripInfrastructureHeaders?: boolean
  }
  export interface JsConvertResult {
    entriesProcessed: number
    mocksCount: number
    content: string
  }
  export interface JsCreateInput {
    url: string
    method?: string
    status?: number
    body?: string
    template?: boolean
    id?: string
    priority?: number
    collection?: string
    format?: string
    /** Mock kind: "http" (default), "ws", or "sse" */
    kind?: string
  }
  export interface JsCreateResult {
    mockId: string
    content: string
  }
  export interface JsExportInput {
    mocksDir?: string
    filter?: string
  }
  export interface JsExportResult {
    content: string
    mocksExported: number
  }
  export interface JsFakeDataInput {
    generator: string
    count?: number
    min?: number
    max?: number
    words?: number
    length?: number
  }
  export interface JsFakeImageInput {
    imageType?: string
    width?: number
    height?: number
    bgColor?: string
    textColor?: string
    text?: string
    initials?: string
    startColor?: string
    endColor?: string
    direction?: string
    imageFormat?: string
    quality?: number
    colored?: boolean
  }
  export interface JsFakeImageResult {
    base64: string
    mimeType: string
  }
  export interface JsFakePdfInput {
    pages?: number
    text?: string
  }
  export interface JsFakePdfResult {
    base64: string
  }
  export interface JsFormatFileResult {
    path: string
    changed: boolean
    error?: string
  }
  export interface JsFormatInput {
    path: string
    check?: boolean
  }
  export interface JsFormatOutput {
    files: Array<JsFormatFileResult>
    formattedCount: number
    errorCount: number
    unchangedCount: number
  }
  export interface JsGeneratorInfo {
    name: string
    category: string
    description: string
    example: string
  }
  export interface JsListInput {
    mocksDir?: string
    filter?: string
  }
  export interface JsListOutput {
    mocks: Array<JsMockSummary>
    total: number
  }
  export interface JsMockSummary {
    id: string
    priority: number
    enabled: boolean
    methods: Array<string>
    urlPatterns: Array<string>
    status: number
    hasHeaderMatchers: boolean
    hasDelay: boolean
    scope?: string
  }
  export interface JsServeInput {
    port?: number
    host?: string
    mocksDir?: string
    mockFile?: string
    watch?: boolean
    cors?: boolean
    verbose?: boolean
  }
  export interface JsServeResult {
    port: number
    url: string
  }
  export interface JsTemplateInput {
    template: string
    context?: any
    count?: number
  }
  export interface JsTestMatchInput {
    method: string
    path: string
    query?: string
    headers?: Record<string, string>
    body?: string
    render?: boolean
    mocksDir?: string
    mockFile?: string
  }
  export interface JsValidateContentInput {
    content: string
    fileFormat: string
  }
  export interface JsValidateInput {
    path: string
  }
  export interface JsValidateOutput {
    isValid: boolean
    totalErrors: number
    totalWarnings: number
    errors: Array<JsValidationError>
    warnings: Array<JsValidationError>
  }
  export interface JsValidationError {
    mockId?: string
    message: string
    errorType: string
    lineNumber?: number
    suggestion?: string
  }
  export function list(input: JsListInput): Promise<JsListOutput>
  export function listGenerators(category?: string | undefined | null, search?: string | undefined | null): Array<JsGeneratorInfo>
  export function renderTemplate(input: JsTemplateInput): Array<string>
  /**
   * Start a standalone mock server using the service layer.
   *
   * Returns the URL and port. The server runs until the process exits.
   * For more control (stop/restart), use the FerrimockServer class instead.
   */
  export function serve(input: JsServeInput): Promise<JsServeResult>
  export function show(mockId: string, mocksDir?: string | undefined | null): Promise<any | null>
  export function testMatch(input: JsTestMatchInput): Promise<any>
  export function validate(input: JsValidateInput): Promise<JsValidateOutput>
  export function validateContent(input: JsValidateContentInput): Promise<JsValidateOutput>
}

export declare namespace ws {
  /**
   * Create a WebSocket handler mock.
   *
   * @param url - Link URL pattern string (`wss://host/path/:param`) or RegExp
   *   (tested against the path and `ws(s)://host/path` reconstructions).
   * @param dispatch - Callback receiving `{ type, connectionId, ... }`
   *   connection events, resolving with whether `preventDefault()` was called.
   */
  export function handler(url: unknown, dispatch: (arg: WsBridgeEvent) => Promise<boolean>): RequestHandler
}
